language: java
install: ant dist

matrix:
  fast_finish: true
  include:
  - os: linux
    jdk: oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - oracle-java8-installer
